name: Install ShellHub Agent

on:
  workflow_dispatch:

jobs:
  install-shellhub:
    runs-on: self-hosted

    steps:
      - name: Install ShellHub Agent
        shell: bash
        env:
          TENANT_ID: ${{ secrets.SHELLHUB_TENANT_ID }}
          SERVER_ADDRESS: https://cloud.shellhub.io
        run: |
          curl -sSf https://cloud.shellhub.io/install.sh | \
            TENANT_ID="$TENANT_ID" \
            SERVER_ADDRESS="$SERVER_ADDRESS" \
            sh
